steps: 
- name: node:16
  entrypoint: npm
  args: ['install']
- name: node:16
  entrypoint: npm
  args: ['run', 'ci']
- name: node:16
  entrypoint: npm
  args: ['run', 'build']
- name: gcr.io/$PROJECT_ID/firebase
  args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']